# Generated by Django 5.2.7 on 2025-10-08 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('Pop', 'Pop'), ('Rap', 'Rap'), ('Reggeton', 'Reggeton'), ('Electronica', 'Electronica')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ano_lanzamiento', models.IntegerField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=10)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(choices=[('CR', 'CIUDAD REAL'), ('ARG', 'ARGAMASILLA'), ('PUER', 'PUERTOLLANO'), ('AML', 'ALMODOVAR')])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.direccion')),
            ],
        ),
    ]
